version: "3"

services:
  elixir:
    container_name: ${HOST}
    tty: true
    build: 
      # Here we define that it should build from the current directory.
      context: .
    volumes:
      - .:/src
    ports:
      - "${PORT}:4000"
    environment:
      HOST: ${HOST}
      PORT: ${PORT}
      PGUSER: ${DB_USERNAME}
      PGPASSWORD: ${DB_PASSWORD}
      PGPORT: ${DB_PORT}
      PGHOST: ${DB_HOST}
    depends_on:
      - database
  database:
    container_name: ${DB_HOST}
    image: postgres:14.3
    tty: true
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    restart: always
    volumes:
      - ./sql-scripts/sandbox-init.sql:/docker-entrypoint-initdb.d/sandbox-init.sql"
      - ./pgdata:/var/lib/postgresql/data
      
volumes:
   pgdata: